# GNU Makefile for vispatch 32 bit DOS binaries using GCC (DJGPP).

CC ?= gcc

OBJECTS:= utilslib.o \
	strlcat.o \
	strlcpy.o \
	vispatch.o

OPTIMIZATIONS= -O2

CFLAGS = -g -Wall -W -Wshadow $(OPTIMIZATIONS)
LDFLAGS= -lc

all: vispatch.exe

.c.o:
	$(CC) $(CFLAGS) -c $*.c

vispatch.exe: $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f *.o *.res *.d

