# GNU Makefile for vispatch 32 bit DOS binaries using GCC (DJGPP).
# $Id: makefile.djgpp,v 1.3 2011-07-15 09:33:49 sezero Exp $

CC ?= gcc

OBJECTS:= utilslib.o \
	strlcat.o \
	strlcpy.o \
	vispatch.o

OPTIMIZATIONS= -O2

CFLAGS = -g -Wall -W -Wshadow $(OPTIMIZATIONS)
LDFLAGS= -lc -lgcc

all: vispatch.exe

.c.o:
	$(CC) $(CFLAGS) -c $*.c

vispatch.exe: $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f *.o *.d

