# GNU Makefile for vispatch windows binaries using GCC (MinGW).
# $Id: makefile.mingw,v 1.3 2009-01-31 08:41:57 sezero Exp $

CC ?= gcc

OBJECTS:= utilslib.o \
	strlcat.o \
	strlcpy.o \
	vispatch.o

OPTIMIZATIONS:= -O2
#OPTIMIZATIONS:= -O -g

CFLAGS := -Wall -W -Wshadow -DWIN32_LEAN_AND_MEAN $(OPTIMIZATIONS)
LDFLAGS:= -mconsole

all: vispatch.exe

.c.o:
	$(CC) $(CFLAGS) -c $*.c

vispatch.exe: $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f *.o *.d

